/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parquederoVistas;

/**
 *
 * @author Usuario
 */
public class VistaLiquidarParqueadero extends javax.swing.JFrame {

    /**
     * Creates new form VistaLiquidarParqueadero
     */
    public VistaLiquidarParqueadero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        CajaHoraEtrada = new javax.swing.JLabel();
        Placa = new javax.swing.JTextField();
        BotonLiquidar = new javax.swing.JButton();
        javax.swing.JLabel jLabel10 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel9 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel96 = new javax.swing.JLabel();
        CajaHoraSalida = new javax.swing.JLabel();
        javax.swing.JLabel jLabel98 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel101 = new javax.swing.JLabel();
        CajaCompañere = new javax.swing.JLabel();
        javax.swing.JLabel jLabel97 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel104 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel106 = new javax.swing.JLabel();
        CajaValorpagar = new javax.swing.JLabel();
        CajaTiempoTotal = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cajaprueba = new javax.swing.JTextField();
        javax.swing.JLabel jLabel100 = new javax.swing.JLabel();
        CajaValor1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Placa");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 76, 59, 24));

        CajaHoraEtrada.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        CajaHoraEtrada.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(CajaHoraEtrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 150, 30));

        Placa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Placa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlacaActionPerformed(evt);
            }
        });
        getContentPane().add(Placa, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 150, 50));

        BotonLiquidar.setBackground(new java.awt.Color(255, 255, 255));
        BotonLiquidar.setForeground(java.awt.Color.red);
        BotonLiquidar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exit.png"))); // NOI18N
        BotonLiquidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLiquidarActionPerformed(evt);
            }
        });
        getContentPane().add(BotonLiquidar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 80, 70));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carsharing.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel9.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("LIQUIDAR");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 100, 20));

        jLabel96.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel96.setForeground(new java.awt.Color(255, 255, 255));
        jLabel96.setText("PLACA:");
        getContentPane().add(jLabel96, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 80, 30));

        CajaHoraSalida.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        CajaHoraSalida.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(CajaHoraSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 150, 30));

        jLabel98.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel98.setForeground(new java.awt.Color(255, 255, 255));
        jLabel98.setText("HORA SALIDA:");
        getContentPane().add(jLabel98, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 140, 30));

        jLabel101.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel101.setForeground(new java.awt.Color(255, 255, 255));
        jLabel101.setText("VALOR A PAGAR");
        getContentPane().add(jLabel101, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 160, 30));

        CajaCompañere.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        CajaCompañere.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(CajaCompañere, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 300, 30));

        jLabel97.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel97.setForeground(new java.awt.Color(255, 255, 255));
        jLabel97.setText("PLACA:");
        getContentPane().add(jLabel97, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 80, 30));

        jLabel104.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel104.setForeground(new java.awt.Color(255, 255, 255));
        jLabel104.setText("TIEMPO PARQUEADO:");
        getContentPane().add(jLabel104, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 160, 30));

        jLabel106.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel106.setForeground(new java.awt.Color(255, 255, 255));
        jLabel106.setText("FECHA ENTRADA:");
        getContentPane().add(jLabel106, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 140, 30));

        CajaValorpagar.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        CajaValorpagar.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(CajaValorpagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 150, 30));

        CajaTiempoTotal.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        CajaTiempoTotal.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(CajaTiempoTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 150, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Negro Amarillo Halcón Moderno Gamer Esports Logotipo Animado (6).png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -280, 500, 1060));

        cajaprueba.setForeground(new java.awt.Color(0, 255, 0));
        cajaprueba.setText("jTextField1");
        getContentPane().add(cajaprueba, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, -1, -1));

        jLabel100.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel100.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel100, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 150, 30));

        CajaValor1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        CajaValor1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(CajaValor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 150, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PlacaActionPerformed

    private void BotonLiquidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLiquidarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonLiquidarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaLiquidarParqueadero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaLiquidarParqueadero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaLiquidarParqueadero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaLiquidarParqueadero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaLiquidarParqueadero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BotonLiquidar;
    public javax.swing.JLabel CajaCompañere;
    public javax.swing.JLabel CajaHoraEtrada;
    public javax.swing.JLabel CajaHoraSalida;
    public javax.swing.JLabel CajaTiempoTotal;
    public javax.swing.JLabel CajaValor1;
    public javax.swing.JLabel CajaValorpagar;
    public javax.swing.JTextField Placa;
    public javax.swing.JTextField cajaprueba;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
